version: '3'

networks:
  default:
  db-net:
  external-network:
    external:
      name: External

services:
  postgres:
    image: postgres
    container_name: postgresql
    volumes:
      - /data/JupyterHub/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${JUPYTERHUB_POSTGRES_DB}
      - POSTGRES_USER=${JUPYTERHUB_POSTGRES_USER}
      - POSTGRES_PASSWORD=${JUPYTERHUB_POSTGRES_PASSWORD}
    entrypoint: /bin/sh -c
    command: ["${JUPYTERHUB_INTERNAL_POSTGRES} && docker-entrypoint.sh postgres"]
    networks:
      - db-net
    restart: always

  jupyterhub:
    container_name: jupyterhub
    image: ahkui/jupyterhub:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /data/JupyterHub/data:/data
      - /data/JupyterHub/user-data:/user-data
      - /data/JupyterHub/admin.txt:/root/.jupyter/admin.txt
      - /data/JupyterHub/jupyterhub_config.py:/root/.jupyter/jupyterhub_config.py
      - /data/JupyterHub/shared.json:/root/.jupyter/shared.json
    env_file: .env
    networks:
      - default
      - db-net
      - external-network
    restart: always

  jupyter-proxy:
    container_name: jupyter_proxy
    image: nginx:alpine
    volumes:
      - ./nginx/proxy.conf:/etc/nginx/conf.d/proxy.conf:ro
    networks:
      - default
      - external-network
    restart: always